### ISSUE TITLE
Redirect old webpage to new one 

### ISSUE THREAD

**Issue by michael-schwarz** [goblint/GobWeb#16]
https://goblint.github.io/ still shows the old one in all of its glory. I guess we would want a `301 Moved Permanently` redirect?

**Comment by sim642** [comment]
Done! GitHub Pages has some aggressive caching, but a force refresh will show the redirect working if you've visited the page before. I added the redirect HTML onto the `gh-pages` branch to preserve the original `index.html` as it was.
