### ISSUE TITLE
Write about our funding

### ISSUE THREAD

**Issue by ivanazuzic** [goblint/GobWeb#17]
We should ask Helmut how to phrase this.

**Comment by michael-schwarz** [comment]
I guess something along the lines of

```Work on Goblint was supported in part by Deutsche Forschungsgemeinschaft (DFG) (47140942/1480 PUMA, 378803395/2428 ConVeY, [other things]) and the Estonian Research Council grant PSG61```

would be the thing to go for?

**Comment by ivanazuzic** [comment]
> I guess something along the lines of
> 
> `Work on Goblint was supported in part by Deutsche Forschungsgemeinschaft (DFG) (47140942/1480 PUMA, 378803395/2428 ConVeY, [other things]) and the Estonian Research Council (PSG61)`
> 
> would be the thing to go for?

Sounds ok, but I don't know if anything is missing. Does this go to the home page?

**Comment by michael-schwarz** [comment]
Maybe you can just email Helmut to get a list of all funding sources on the TUM side we'd need to acknowledge?
@vesalvojdani should know about any Tartu sources on top of this grant, I guess

**Comment by vesalvojdani** [comment]
An important TUM funding source during my time was [MBAT](http://www.mbat-artemis.eu/home/). I'm actually not sure any PUMA student worked on Goblint, but it doesn't hurt to mention it, as long as we don't include the ugly PUMA logo that I designed. That was my big contribution (or detribution, retribution, ...) to the PUMA project. :)  Tartu sources does include one more we acknowledged in the ASE paper, it's just called [IUT2-1](https://www.etis.ee/Portal/Projects/Display/561b7b1d-d1dd-43a2-90e5-0661de823823?lang=ENG), so it would be good to inlcude these URLs.

**Comment by michael-schwarz** [comment]
So I guess this far we have

> Work on Goblint was supported in part by Deutsche Forschungsgemeinschaft (DFG) (47140942/1480 [PUMA](https://gepris.dfg.de/gepris/projekt/47140942), 378803395/2428 [ConVeY](http://convey.in.tum.de), [other things]), ARTEMIS Joint Undertaking  (269335 [MBAT](http://www.mbat-artemis.eu/home/)), and the Estonian Research Council ([IUT2-1](https://www.etis.ee/Portal/Projects/Display/561b7b1d-d1dd-43a2-90e5-0661de823823?lang=ENG), [PSG61](https://www.etis.ee/Portal/Projects/Display/743243bb-15c2-47b3-9c10-e7d86a9a276d?lang=ENG)).

**Comment by michael-schwarz** [comment]
> as long as we don't include the ugly PUMA logo that I designed. That was my big contribution (or detribution, retribution, ...) to the PUMA project. :) 

Off-Topic: ConVeY is sadly still missing a mascot :sob: Our colleague from LMU suggested a unicorn, but that never went anywhere. We actually admire the Puma logo, the ConVeY "logo" are the yellow letters on blue background at convey.in.tum.de.

**Comment by michael-schwarz** [comment]
I added these to the footer now. [See here](https://goblint.in.tum.de). 
@vogler you were funded through some EU thing as well, was that MBAT? Or something else we should also acknowledge?

Logos would also be nice, but I'm too lazy to figure out all of this angular things for now,

**Comment by vogler** [comment]
> @vogler you were funded through some EU thing as well, was that MBAT? Or something else we should also acknowledge?

In the beginning some MBAT, and then this: http://assume-project.eu
