### ISSUE TITLE
Update paper list

### ISSUE THREAD

**Issue by michael-schwarz** [goblint/GobWeb#33]
- TD: An exercise in A^2I has appeared
- setjmp/longjmp has appeared
- Octagons Revisited is accepted

**Comment by sim642** [comment]
Apparently "Enhancing top-down solving with widening and narrowing" from 2016 is also missing from the website. I didn't even know it existed before seeing it in the A²I references.

**Comment by sim642** [comment]
> Apparently "Enhancing top-down solving with widening and narrowing" from 2016 is also missing from the website.

Reopening because #34 didn't add this. Otherwise this comment is forgotten forever.

**Comment by michael-schwarz** [comment]
Done in #39.
