### ISSUE TITLE
Conflicting paper entry for "Global invariants for analysing multi-threaded applications"

### ISSUE THREAD

**Issue by sim642** [goblint/GobWeb#42]
https://github.com/goblint/GobWeb/blob/65bb2fcf5158a935080653dec993174a12cc0df2/src/app/papers.ts#L813-L830

The website shows "NWPT 2002", but the BibTeX to be copied is for 2003 and another venue.

**Comment by michael-schwarz** [comment]
This is likely a case of me trusting chatgpt to do some of the reformatting and not properly verifying it does something meaningful :upside_down_face:
