### ISSUE TITLE
Authors and contact

### ISSUE THREAD

**Issue by ivanazuzic** [goblint/GobWeb#5]
Authors are currently placed at the bottom of the overview page. Should they get their own page?
Do we want to give some contact email? It used to say that people should contact Vesal regarding Goblint, but I'm unsure if that's the way to go.

**Comment by michael-schwarz** [comment]
Maybe a people page. There we could also list all students who worked on it in the (recent) past and provide photos of main developers

**Comment by ivanazuzic** [comment]
The final decision about the categories of members we want to show.

- Current core team (active on Slack, GobCon or commits)
- Past contributors: phd, master, bachelor

**Comment by vesalvojdani** [comment]
Okay, so we have the "Current Team Members" and I wanted to simplify the titles.
- Helmut Seidl, Chief Fixpoint Officer.
- Kalmer Apinis, Chief Widening Officer.
- Julian Erhard, Chief Soundness Officer.
- Simmo Saan, Chief Witness Officer.
- Michael Schwarz, Chief Accessibility Officer.
- Ralf Vogler, Chief Top-Down Officer.
- Vesal Vojdani, Chief Race and Diversity Officer.
- Ivana Zuzic, Chief Public Relational Domains Officer.
- Wettlaufweltmeister, Organization Mascot.
So, chief accessibility and diversity officers are actually real jobs, it seems. Maybe we go with "chief array accessibility officer" to avoid people e-mailing Michael that Goblint lacks text-to-speech functionality.

**Comment by vesalvojdani** [comment]
OMG, how could I have missed it... now it hit me out of nowhere: Ralf is obviously The Chief Executability Officer! (I mean Docker cloud... such a CEO thing to do.) So here's the updated list:
- Helmut Seidl, Chief Fixpoint Officer.
- Kalmer Apinis, Chief Widening Officer.
- Julian Erhard, Chief Soundness Officer.
- Simmo Saan, Chief Witness Officer.
- Michael Schwarz, Chief Array Accessibility Officer.
- Ralf Vogler, Chief Executability Officer.
- Vesal Vojdani, Chief Race and Diversity Officer.
- Ivana Zuzic, Chief Public Relational Domains Officer.
- Wettlaufweltmeister, Chief Organization Mascot.

**Comment by michael-schwarz** [comment]
Do we still want to follow-up on this? Or should we close the issue?
